package com.liferay.docs.infos.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the District service. Represents a row in the &quot;infos_District&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.docs.infos.model.impl.DistrictModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.docs.infos.model.impl.DistrictImpl}.
 * </p>
 *
 * @author Joe Bloggs
 * @see District
 * @see com.liferay.docs.infos.model.impl.DistrictImpl
 * @see com.liferay.docs.infos.model.impl.DistrictModelImpl
 * @generated
 */
public interface DistrictModel extends BaseModel<District> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a district model instance should use the {@link District} interface instead.
     */

    /**
     * Returns the primary key of this district.
     *
     * @return the primary key of this district
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this district.
     *
     * @param primaryKey the primary key of this district
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the district ID of this district.
     *
     * @return the district ID of this district
     */
    public long getDistrictId();

    /**
     * Sets the district ID of this district.
     *
     * @param districtId the district ID of this district
     */
    public void setDistrictId(long districtId);

    /**
     * Returns the company ID of this district.
     *
     * @return the company ID of this district
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this district.
     *
     * @param companyId the company ID of this district
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the group ID of this district.
     *
     * @return the group ID of this district
     */
    public long getGroupId();

    /**
     * Sets the group ID of this district.
     *
     * @param groupId the group ID of this district
     */
    public void setGroupId(long groupId);

    /**
     * Returns the user ID of this district.
     *
     * @return the user ID of this district
     */
    public long getUserId();

    /**
     * Sets the user ID of this district.
     *
     * @param userId the user ID of this district
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this district.
     *
     * @return the user uuid of this district
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this district.
     *
     * @param userUuid the user uuid of this district
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the create date of this district.
     *
     * @return the create date of this district
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this district.
     *
     * @param createDate the create date of this district
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this district.
     *
     * @return the modified date of this district
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this district.
     *
     * @param modifiedDate the modified date of this district
     */
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the name of this district.
     *
     * @return the name of this district
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this district.
     *
     * @param name the name of this district
     */
    public void setName(String name);

    /**
     * Returns the code of this district.
     *
     * @return the code of this district
     */
    public int getCode();

    /**
     * Sets the code of this district.
     *
     * @param code the code of this district
     */
    public void setCode(int code);

    /**
     * Returns the is archived of this district.
     *
     * @return the is archived of this district
     */
    public boolean getIsArchived();

    /**
     * Returns <code>true</code> if this district is is archived.
     *
     * @return <code>true</code> if this district is is archived; <code>false</code> otherwise
     */
    public boolean isIsArchived();

    /**
     * Sets whether this district is is archived.
     *
     * @param isArchived the is archived of this district
     */
    public void setIsArchived(boolean isArchived);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.liferay.docs.infos.model.District district);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.liferay.docs.infos.model.District> toCacheModel();

    @Override
    public com.liferay.docs.infos.model.District toEscapedModel();

    @Override
    public com.liferay.docs.infos.model.District toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
